reconciliation/urls.py
from django.contrib import admin
from django.urls import path

from reconciliation.views import reconciliation_view


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", reconciliation_view),
]

reconciliation/forms.py
from django import forms
from django.core.validators import FileExtensionValidator


class CSVUploadForm(forms.Form):
    """
    CSV file upload form
    """

    first_file = forms.FileField(validators=[FileExtensionValidator(["csv"])])
    second_file = forms.FileField(validators=[FileExtensionValidator(["csv"])])

reconciliation/views.py
import pandas as pd
from django.shortcuts import render
from process.reconcile import pre_process, reconcile

from reconciliation.forms import CSVUploadForm


def process_file(source, target):
    """
    This is the main function used to reconcile data

    Parameters
    ----------
    source : File
        Source file .
    target : File
        Target file.

    Returns
    -------
    Dict
        The difference between source and target files

    """
    source_df = pd.read_csv(source, index_col=0, skipinitialspace=True)
    target_df = pd.read_csv(target, index_col=0, skipinitialspace=True)

    cleaned_source_df, cleaned_target_df = pre_process(source_df, target_df)
    difference = reconcile(cleaned_source_df, cleaned_target_df)

    return difference


def reconciliation_view(request):
    if request.method == "POST":
        form = CSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            source_file, target_file = request.FILES.values()
            difference = process_file(source_file, target_file)
            return render(request, "report.html", {"difference": difference})
    else:
        form = CSVUploadForm()

    return render(
        request,
        "reconciliation_page.html",
        {"form": form, "errors": form.errors},
    )

reconciliation/templates/reconciliation_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{% static 'reconciliation/reconciliation_page.css' %}"
    />
    <title>Reconciliation</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Reconcile</span>
      </div>
    </nav>
    <div class="file-upload">
      <div class="card">
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_first_file" class="form-label" for>Upload source</label>
                    <input class="form-control" type="file" name="first_file" for="id_first_file"/>
                    <span class="error">{{errors.first_file}}</span>
                </div>
                <div class="mb-3">
                    <label for="id_second_file" class="form-label">Upload target</label>
                    <input class="form-control" type="file" name="second_file" id="id_second_file"/>
                    <span class="error">{{errors.second_file}}</span>

                </div>
                <button type="submit" class="btn btn-primary">Reconcile</button>
                
            </form>
          
      </div>
    </div>
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
  </body>
</html>

reconciliation/templates/report.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'reconciliation/report.css' %}" />
  </head>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Report</span>
    </div>
  </nav>
  <body>
    <div class="container">
      <button class="btn btn-light" onClick="history.back()">Back</button>
                
      <div class="card">
        <div class="card-body">
        <table class="table table-light table-striped">
          <thead>
            <tr class="table-primary">
              <th> Type</th>
              <th> Record identifier</th>
              <th> Field</th>
              <th> Source value</th>
              <th> Target value</th>
            </tr>
          </thead>
          <tbody>
            {% for key, values in difference.items %} 
              {% for index,targetValue, sourceValue in values %} 
                
                {% if targetValue is None %} 
                <tr>
                    <td>Missing in target</td>
                    <td>{{index}}</td>
                    <td>{{key}}</td>
                    <td>{{sourceValue}}</td>
                    <td>{{ targetValue}}</td>
                  </tr>
                  
                {% endif %} 
                  
              {% endfor %}
            {% endfor %}
            {% for key, values in difference.items %} 
              {% for index,targetValue, sourceValue in values %} 
                
                {% if sourceValue is None %} 
                <tr>
                    <td>Missing in source</td>
                    <td>{{index}}</td>
                    <td>{{key}}</td>
                    <td>{{sourceValue}}</td>
                    <td>{{ targetValue}}</td>
                  </tr>
                  
                {% endif %} 
                  
              {% endfor %}
            {% endfor %}
            {% for key, values in difference.items %} 
              {% for index,targetValue, sourceValue in values %} 
                
                {% if targetValue is not None and sourceValue is not None %} 
                <tr>
                    <td>Field discrepancy</td>
                    <td>{{index}}</td>
                    <td>{{key}}</td>
                    <td>{{sourceValue}}</td>
                    <td>{{ targetValue}}</td>
                  </tr>
                  
                {% endif %} 
                  
              {% endfor %}
            {% endfor %}
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </body>
  
</html>